### ISSUE TITLE
Setup react routing

### ISSUE THREAD

**Issue by jordansimsmith** [softeng-701-group-5/softeng-701-assignment-1#37]
**User Story**
As a frontend developer, I'd like to set up client routing, so that I can navigate between pages.

**Acceptance Criteria**

- React router dom installed.
- React router navigation setup to switch between landing and feed page.
- Skeleton `HomePage.jsx` created with (material ui) button to link to feed page
- Home button in AppBar in feedpage links back to home page
- Unit tests added as appropriate (test routing)

**Notes**

**Comment by Kalashnikkov** [comment]
👍 , Looking forward in seeing how our landing page will look like alongside the main feed page

**Comment by AlexanderTheGrape** [comment]
Why do we need a landing page? I thought this was meant to be just a one-page website

**Comment by Matteas-Eden** [comment]
The landing page is a placeholder for a stretch goal of hooking into OAuth. It's still a single-page application (because we don't use server-side rendering and there's a single HTML file that gets modified at runtime), but there is more than one 'page', so-to-speak. The landing page will redirect to the main page (where the feed is displayed), but it's all one HTML file - so therefore still considered a single-page application. I agree the terminology can be confusing.
