### ISSUE TITLE
Add documentation for backend testing procedure

### ISSUE THREAD

**Issue by jordansimsmith** [softeng-701-group-5/softeng-701-assignment-1#69]
**User Story**

As a backend developer, I'd like to define the process of unit testing on the backend, so that new collaborators are comfortable with the process.

**Acceptance Criteria**
- Usage of JUnit 5 explained
- Usage of mockito explained
- Usage of `@SpringBootTest` and `@Autowired` annotations explained (and other relevant annotations)

**Notes**
(documentation should explain how to use, what each concept is and why we are using it).
If you are not a merger, send the documentation to @Matteas-Eden and he can upload it for you.

**Comment by TCHE614** [comment]
**Backend Unit Testing:**
Unit testing is essential in software development, as we can test individual components. Therefore, using JUnit, Mockito and other testing annotations, we can validate and ensure the function performs as desired. JUnit is a testing method, Mockito is testing using mock objects, the other annotations we use are @Autowired and @WebFluxTest, @Autowired is linked with Mockito and WebFluxTest is a Spring Boot controller test.

**Junit 5:**
JUnit 5 is a widely used unit testing framework for Java applications, JUnit allows users to define system behaviour with these tests. The JUnit tests are a continuous integration in the server, compared to manual testing such as System.out it is significantly better. Using JUnit as a framework allows us to test each unit’s behaviour automatically. 

How to use:
There are ten annotations that can be written into the code. Each annotation must be written before a test method in the test class. The test files, located in the test folder, have examples of how we tested the code.
 
![JUnit](https://user-images.githubusercontent.com/48304096/76712113-6c5e1e80-677a-11ea-872f-8e60c985ef74.png)

Using @BeforeEach we can ensure that our test cases are running in the order we specified. The @BeforeEach test allows us to test our parameter injection without the proper values, ensuring that the setup is allowed.

**Mockito:**
Mockito builds on top of the JUnit framework. The primary purpose of Mockito is testing with mock objects. Using mock objects, we can validate that the class reacts correctly.  When using Mockito, we use the @MockBean annotation, we used @Mockbean instead of @Mock because we are using a Spring Boot library wrapping the Mockito library. So, using @MockBean allows us to rely on the Spring Boot container to add or mock one of the container beans (Basically @Mock but with Spring support). 

How to use:
MockBean is usually used alongside @WebFluxTest; we use the MockBean to provide a mock implementation in the controller class. We can create @MockBean fields and classes to tell the mock how to behave when methods are called on it. 

**@Autowired:**
The Autowired annotation allows us to inject collaborating beans into existing beans. The main benefit of Autowired annotation removes the need for us to do wiring in the XML file and finds the dependencies for us. The @Autowired annotation tells Spring where an injection needs to be.

How to use:
Autowired is used on properties, setters and constructors. Using Autowired on properties removes the need for getters and setters. Using @Autowired on a private field, Spring will find and inject the @Autowired property when the class is called. We also used @Autowired on constructors. When @Autowired is used on a constructor, the instance of the private variable is injected as an argument into the constructor when the class is called.

**@WebFluxTest**
Since we are using the Spring Boot Webflux to test our controller, we need to use WebFluxTest. WebFluxTest is usually used alongside @MockBean to create any collaborators required by the @Controller bean.

How to use:
Using @WebFluxTest we disable full auto-configuration and apply only the relevant configurations to WebFlux. To use WebFluxTest add the annotation before the class that you would like to test and link the annotation to the class that is mocked. Within the class, you can add configurations relevant to WebFlux and only those will be ran. 

@jordansimsmith This is what I have right now.  @Minus20Five  and @HarrisonLeach1 is there anything big that I missed

**Comment by jordansimsmith** [comment]
Nice work @TCHE614! I've made a couple of edits and have put it in the wiki. Thanks a lot :tada:
