### ISSUE TITLE
Document application architecture

### ISSUE THREAD

**Issue by jordansimsmith** [softeng-701-group-5/softeng-701-assignment-1#70]
**User Story**

As a developer, I'd like to document the architecture of the application, so that new collaborators can quickly gain a high level understanding.

**Acceptance Criteria**

- Architecture diagram created, showing API calls between client, server and api providers
- Shows relevant technologies at each service (React for client, Spring for backend etc.) Elaborate on this.
- Explain intent behind these architectural decisions.

**Notes**  
If you need clarification on our decisions, contact @jordansimsmith , @Minus20Five , @HarrisonLeach1 , @harmanlamba as we were directly involved.

If you are not a merger, contact @Matteas-Eden or @jordansimsmith to add the page to the wiki.

**Comment by utri092** [comment]
I plan to add a flowchart/written documentation for the github api. Working closely with @Matteas-Eden and @DeshmukhChinmay to make sure this goes smoothly.

**Comment by salma-s** [comment]
Some of these ACs have since been addressed in the Wiki. AC for architectual decisions explained in [Server and APIs](https://github.com/softeng-701-group-5/softeng-701-assignment-1/wiki/Server-and-APIs), AC for explaining relevant technologies addressed in [Loging and Feed Page](https://github.com/softeng-701-group-5/softeng-701-assignment-1/wiki/Login-and-Feed-Page) as well as the frontend and backend testing pages.
